# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-05-31T22:30:16+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PubSubMessage(BaseModel):
    data: str = Field(..., description="encoded data message")
    messageId: str = Field(..., description="unique data message identifier")
    publishTime: Optional[str] = Field(None, description="message published timestamp")


class PubSubRequest(BaseModel):
    message: PubSubMessage
